on:
  workflow_dispatch: 

permissions: 
   contents: read
   issues: write
   copilot-requests: write 
env:
  COPILOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authorizes the Copilot AI Engine
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}             # Authorizes the 'gh' CLI tool to create the issue
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
  
jobs: 
  agent-task: 
    runs-on: ubuntu-latest
 
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4
      
      - name: Agent Task - Review for vulnerabilities
        run: |
          npx @github/copilot \
          -p "Review code and dependencies for vulnerabilities and create issue" \
          --no-ask-user \
          --allow-tool shell \
          --allow-url api.github.com
          
